function [F,J] = SSY_in_t(t,a,tau_b,dP_inj,dP_prod,dt_prod,...
                          f_r,Pi,Pi_prime,interp_k_diff,interp_dk_diff)

%% - Overpressure

P = (dP_inj-dP_prod) * Pi(a/t) ...
  + dP_prod * Pi(a/sqrt(t^2+dt_prod^2));

dP_dt = ...
    -(dP_inj-dP_prod) * a/t^2 * Pi_prime(a/t) ...
    - dP_prod * a*t/(t^2+dt_prod^2)^(3/2) ...
      * Pi_prime(a/sqrt(t^2+dt_prod^2));

%% - Effective crack length

a_eff = a - (pi/2*0.466^2)/(1-P);

da_eff_dt = ...
    -(pi/2*0.466^2) * dP_dt/(1-P)^2;

%% - Mode II stress intensity factor

% Diffusive contribution
k_II_diff = ...
    (dP_inj-dP_prod) * interp_k_diff(a_eff/t) ...
    + dP_prod * interp_k_diff(a_eff/sqrt(t^2+dt_prod^2));

dk_II_diff_da_eff = ...
    (dP_inj-dP_prod)/t ...
    * interp_dk_diff(a_eff/t) ...
    + dP_prod/sqrt(t^2+dt_prod^2) ...
    * interp_dk_diff(a_eff/sqrt(t^2+dt_prod^2));

dk_II_diff_dt = ...
    -(dP_inj-dP_prod) * a/t^2 ...
    * interp_dk_diff(a_eff/t) ...
    - dP_prod * a*t/(t^2+dt_prod^2)^(3/2) ...
    * interp_dk_diff(a_eff/sqrt(t^2+dt_prod^2));

%% - Total stress intensity factor

K_II = sqrt(pi*a_eff) * ...
       (tau_b - f_r + f_r*k_II_diff);

dK_II_da_eff = ...
    0.5*K_II/a_eff ...
    + sqrt(pi*a_eff)*f_r*dk_II_diff_da_eff;

dK_II_dt = ...
    dK_II_da_eff*da_eff_dt ...
    + sqrt(pi*a_eff)*f_r*dk_II_diff_dt;

%% - Local fracture toughness

K_IIc = (1-f_r)*sqrt(1-P);

dK_IIc_dt = ...
    -(1-f_r)*0.5*dP_dt/sqrt(1-P);

%% - Objective function

F = K_II - K_IIc;

%% - Jacobian

J = dK_II_dt - dK_IIc_dt;

end